# Generated by Django 4.2.6 on 2023-10-22 23:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name_plural": "categories"},
        ),
        migrations.AlterModelOptions(
            name="maintenance",
            options={"verbose_name_plural": "maintenance tasks"},
        ),
        migrations.AlterField(
            model_name="waypoint",
            name="latitude",
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
        migrations.AlterField(
            model_name="waypoint",
            name="longitude",
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
    ]
