# Generated by Django 4.2.6 on 2023-10-24 22:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0002_alter_category_options_alter_maintenance_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="maintenance",
            name="next_scheduled",
            field=models.DateField(null=True, default=None),
        ),
        migrations.AlterField(
            model_name="maintenance",
            name="last_performed",
            field=models.DateField(blank=True),
        ),
    ]
