# Generated by Django 4.2.6 on 2023-10-25 00:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0003_maintenance_next_scheduled_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="maintenance",
            options={
                "verbose_name": "maintenance task",
                "verbose_name_plural": "maintenance tasks",
            },
        ),
        migrations.AddField(
            model_name="maintenance",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="inventory.category",
            ),
        ),
    ]
