# Generated by Django 4.2.6 on 2023-10-25 00:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0004_alter_maintenance_options_maintenance_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="maintenance",
            name="last_performed",
            field=models.DateField(default=None, null=True),
        ),
    ]
