# Generated by Django 4.2.6 on 2023-10-25 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0005_alter_maintenance_last_performed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="maintenance",
            name="item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="inventory.item",
            ),
        ),
        migrations.AlterField(
            model_name="maintenance",
            name="last_performed",
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="maintenance",
            name="next_scheduled",
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
