# Generated by Django 4.2.6 on 2023-10-25 20:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0006_alter_maintenance_item_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="maintenance",
            name="requires_items",
            field=models.ManyToManyField(related_name="used_for", to="inventory.item"),
        ),
    ]
