# Generated by Django 4.2.6 on 2023-10-26 01:40

from django.db import migrations, models
import django.db.models.deletion
import inventory.models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0008_rename_item_maintenance_target_item"),
    ]

    operations = [
        migrations.CreateModel(
            name="Documents",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("document", models.JSONField()),
            ],
            bases=(models.Model, inventory.models.UrlMixin),
        ),
        migrations.AddField(
            model_name="item",
            name="document",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="inventory.documents",
            ),
        ),
    ]
