# Generated by Django 4.2.6 on 2023-10-27 21:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0009_documents_item_document"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="item",
            name="document",
        ),
        migrations.DeleteModel(
            name="Documents",
        ),
    ]
