# Generated by Django 4.2.6 on 2023-10-27 22:31

from django.db import migrations, models
import django.db.models.deletion
import inventory.models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0010_remove_item_document_delete_documents"),
    ]

    operations = [
        migrations.CreateModel(
            name="ItemType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "properties",
                    models.JSONField(
                        help_text="Provied a list of field names for populating Item.extra",
                        null=True,
                    ),
                ),
            ],
            bases=(models.Model, inventory.models.UrlMixin),
        ),
        migrations.AddField(
            model_name="item",
            name="extra",
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name="item",
            name="item_type",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="inventory.itemtype",
            ),
        ),
    ]
